name: agreda
channels:
  - defaults
dependencies:
  - pyzmq=23.2.0
  - prompt-toolkit=3.0.20
  - threadpoolctl=2.2.0
  - numpy-base=1.21.5
  - glib=2.69.1
  - libgfortran-ng=7.5.0
  - libxkbcommon=1.0.1
  - argon2-cffi=21.3.0
  - markupsafe=2.1.1
  - qtconsole=5.3.2
  - libuuid=1.0.3
  - libtasn1=4.16.0
  - sniffio=1.2.0
  - nest-asyncio=1.5.5
  - pcre=8.45
  - _openmp_mutex=5.1
  - joblib=1.1.0
  - libev=4.33
  - prompt_toolkit=3.0.20
  - qtwebkit=5.212
  - typing_extensions=4.3.0
  - anyio=3.5.0
  - argon2-cffi-bindings=21.2.0
  - qt-webengine=5.15.9
  - libbrotlienc=1.0.9
  - qtpy=2.2.0
  - seaborn=0.11.2
  - igraph=0.9.8
  - nettle=3.7.3
  - libpng=1.6.37
  - lzo=2.10
  - pyqt=5.15.7
  - typing-extensions=4.3.0
  - matplotlib-base=3.5.1
  - parso=0.8.3
  - freetype=2.11.0
  - natsort=7.1.1
  - ipython_genutils=0.2.0
  - bzip2=1.0.8
  - websocket-client=0.58.0
  - beautifulsoup4=4.11.1
  - ffmpeg=4.2.2
  - libllvm11=11.1.0
  - numexpr=2.8.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - urllib3=1.26.11
  - openh264=2.1.1
  - ptyprocess=0.7.0
  - _libgcc_mutex=0.1
  - libvpx=1.7.0
  - libbrotlidec=1.0.9
  - libxslt=1.1.35
  - tqdm=4.64.0
  - jupyterlab_pygments=0.1.2
  - gstreamer=1.14.0
  - libopus=1.3.1
  - libwebp-base=1.2.2
  - terminado=0.13.1
  - pysocks=1.7.1
  - libblas=3.9.0
  - decorator=5.1.1
  - importlib-metadata=4.11.3
  - munkres=1.1.4
  - pytorch=1.12.1
  - krb5=1.19.2
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - sphinx=5.0.2
  - widgetsnbextension=3.5.2
  - libstdcxx-ng=11.2.0
  - libwebp=1.2.2
  - mkl=2021.4.0
  - nbformat=5.3.0
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - numba=0.55.1
  - python=3.10.4
  - x264=1!157.20191217
  - ipython=8.4.0
  - readline=8.1.2
  - jupyter=1.0.0
  - jupyterlab_server=2.12.0
  - cycler=0.11.0
  - umap-learn=0.5.3
  - attrs=21.4.0
  - libsodium=1.0.18
  - sphinxcontrib-qthelp=1.0.3
  - brotli-bin=1.0.9
  - pytables=3.7.0
  - stack_data=0.2.0
  - jedi=0.18.1
  - nbconvert=6.4.4
  - python-igraph=0.9.10
  - cryptography=37.0.1
  - session-info=1.0.0
  - json5=0.9.6
  - jupyter_console=6.4.3
  - libnghttp2=1.46.0
  - xz=5.2.5
  - nss=3.74
  - zeromq=4.3.4
  - debugpy=1.5.1
  - libbrotlicommon=1.0.9
  - traitlets=5.1.1
  - backcall=0.2.0
  - ncurses=6.3
  - python-fastjsonschema=2.16.2
  - sqlite=3.39.2
  - six=1.16.0
  - zipp=3.8.0
  - libffi=3.3
  - gnutls=3.6.15
  - libunistring=0.9.10
  - c-ares=1.18.1
  - mkl-service=2.4.0
  - toml=0.10.2
  - matplotlib-venn=0.11.7
  - prometheus_client=0.14.1
  - certifi=2022.6.15
  - pyrsistent=0.18.0
  - giflib=5.2.1
  - qt-main=5.15.2
  - ply=3.11
  - libidn2=2.3.2
  - stdlib-list=0.7.0
  - pynndescent=0.5.4
  - fontconfig=2.13.1
  - blosc=1.21.0
  - libtiff=4.4.0
  - soupsieve=2.3.1
  - pandas=1.4.3
  - gmp=6.2.1
  - snowballstemmer=2.2.0
  - cffi=1.15.1
  - matplotlib=3.5.1
  - zlib=1.2.12
  - tk=8.6.12
  - idna=3.3
  - bottleneck=1.3.5
  - numpy=1.21.5
  - pure_eval=0.2.2
  - scanpy=1.9.1
  - jpeg=9e
  - liblapack=3.9.0
  - h5py=3.6.0
  - jupyter_client=7.3.5
  - patsy=0.5.2
  - tzdata=2022a
  - ipykernel=6.15.2
  - python-dateutil=2.8.2
  - brotli=1.0.9
  - asttokens=2.0.5
  - setuptools=63.4.1
  - libxml2=2.9.14
  - statsmodels=0.13.2
  - pyparsing=3.0.9
  - mpfr=4.0.2
  - wheel=0.37.1
  - icu=58.2
  - jupyterlab_widgets=1.0.0
  - pytorch-mutex=1.0
  - mistune=0.8.4
  - docutils=0.18.1
  - webencodings=0.5.1
  - ld_impl_linux-64=2.38
  - wcwidth=0.2.5
  - networkx=2.8.4
  - glpk=4.65
  - arpack=3.7.0
  - anndata=0.8.0
  - requests=2.28.1
  - psutil=5.9.0
  - lame=3.100
  - pycparser=2.21
  - fonttools=4.25.0
  - leidenalg=0.8.10
  - ignite=0.4.10
  - pandocfilters=1.5.0
  - llvmlite=0.38.0
  - nspr=4.33
  - sphinxcontrib-htmlhelp=2.0.0
  - bleach=4.1.0
  - torchaudio=0.12.1
  - libclang=10.0.1
  - cached-property=1.5.2
  - jinja2=3.0.3
  - sphinxcontrib-devhelp=1.0.2
  - torchvision=0.13.1
  - jupyter_server=1.18.1
  - jupyterlab=3.4.5
  - jupyter_core=4.10.0
  - zstd=1.5.2
  - pytz=2022.1
  - pillow=9.2.0
  - babel=2.9.1
  - dbus=1.13.18
  - expat=2.4.4
  - sphinxcontrib-serializinghtml=1.1.5
  - notebook=6.4.12
  - scipy=1.7.3
  - jsonschema=4.4.0
  - gst-plugins-base=1.14.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - alabaster=0.7.12
  - pyopenssl=22.0.0
  - lz4-c=1.9.3
  - libpq=12.9
  - entrypoints=0.4
  - openssl=1.1.1q
  - matplotlib-inline=0.1.6
  - texttable=1.6.4
  - libgcc-ng=11.2.0
  - metis=5.1.0
  - sphinxcontrib-applehelp=1.0.2
  - blas=1.0
  - libevent=2.1.12
  - lcms2=2.12
  - suitesparse=5.10.1
  - send2trash=1.8.0
  - executing=0.8.3
  - libcurl=7.84.0
  - pygments=2.11.2
  - mkl_random=1.2.2
  - pexpect=4.8.0
  - ipywidgets=7.6.5
  - kiwisolver=1.4.2
  - nbclient=0.5.13
  - libxcb=1.15
  - packaging=21.3
  - mkl_fft=1.3.1
  - sip=6.6.2
  - tornado=6.2
  - colorama=0.4.5
  - pip=22.1.2
  - scikit-learn=1.1.1
  - libssh2=1.10.0
  - mock=4.0.3
  - nbclassic=0.3.5
  - pickleshare=0.7.5
  - python_abi=3.10
  - sphinxcontrib-jsmath=1.0.1
  - cudatoolkit=11.3.1
  - hdf5=1.12.1
  - lerc=3.0
  - charset-normalizer=2.0.4
  - libgfortran4=7.5.0
  - tbb=2021.5.0
  - testpath=0.6.0
  - imagesize=1.4.1
  - defusedxml=0.7.1
