data_params:
  all_genes: false
  data_dir: data
  dset: pdac
  n_markers: 80
  n_mix: 30
  n_spots: 100000
  one_model: true
  samp_split: false
  sc_id: CA001063
  scaler_name: standard
  st_id: GSE111672
  st_split: false
lib_params:
  manual_seed: 1075059343
model_params:
  coral_kwargs:
    batchnorm: true
    batchnorm_after_act: true
    dropout: 0.1
    emb_dim: 64
    enc_hidden_layer_sizes:
      - 256
      - 128
    enc_out_act: true
    hidden_act: relu
    predictor_hidden_layer_sizes: null
    use_predictor: true
  model_version: final
train_params:
  batch_size: 128
  epochs: 200
  lambda:
    - 0
    - 200
  opt_kwargs:
    lr: 0.0001
    weight_decay: 0.1
  reverse_val: false
