data_params:
  all_genes: false
  data_dir: data
  dset: "mouse_cortex"
  n_markers: 20
  n_mix: 10
  n_spots: 2000
  sample_id_n: "151673"
  scaler_name: standard
  sc_id: "spotless_mouse_cortex"
  st_id: "spotless_mouse_cortex"
  st_split: false
  samp_split: true
model_params:
  coral_kwargs:
    batchnorm: true
    batchnorm_after_act: true
    dropout: 0.5
    enc_hidden_layer_sizes:
      - 1024
      - 512
    hidden_act: leakyrelu
    emb_dim: 64
    enc_out_act: leakyrelu
    predictor_hidden_layer_sizes: null
  model_version: coral_spotless
lib_params:
  manual_seed: 3867
train_params:
  batch_size: 16
  early_stop_crit_adv: 100
  epochs: 100
  lambda: 100
  min_epochs_adv: 40.0
  opt_kwargs:
    lr: 0.0001
    weight_decay: 0.3
  two_step: true
