data_params:
  all_genes: false
  data_dir: data
  dset: dlpfc
  n_markers: 80
  n_mix: 10
  n_spots: 100000
  samp_split: true
  sc_id: GSE144136
  scaler_name: standard
  st_id: spatialLIBD
  st_split: false
lib_params:
  manual_seed: 3666535374
model_params:
  coral_kwargs:
    batchnorm: true
    batchnorm_after_act: true
    dropout: 0.2
    emb_dim: 32
    enc_hidden_layer_sizes:
      - 256
      - 128
    enc_out_act: true
    hidden_act: leakyrelu
    predictor_hidden_layer_sizes: null
    use_predictor: true
  model_version: gen_dlpfc_dlpfc-182188
train_params:
  batch_size: 512
  epochs: 200
  lambda:
    - 200
    - 200
  opt_kwargs:
    lr: 0.01
    weight_decay: 0.3
  reverse_val: false
