data_params:
  all_genes: false
  data_dir: data
  n_markers: 20
  n_mix: 8
  n_spots: 20000
  sample_id_n: "151673"
  scaler_name: standard
  st_split: false
model_params:
  coral_kwargs:
    batchnorm: true
    batchnorm_after_act: true
    dropout: 0.5
    enc_hidden_layer_sizes:
      - 1024
      - 1024
      - 1024
      - 256
    hidden_act: leakyrelu
    emb_dim: 64
    enc_out_act: leakyrelu
    use_predictor: true
    predictor_hidden_layer_sizes: null
  model_version: deep_coral
lib_params:
  manual_seed: 263
train_params:
  batch_size: 512
  early_stop_crit_adv: 100
  epochs: 500
  lambda: 200
  min_epochs_adv: 40.0
  opt_kwargs:
    lr: 0.001
    weight_decay: 0.1
  two_step: true
