data_params:
  all_genes: false
  data_dir: data
  n_markers: 20
  n_mix: 8
  n_spots: 200000
  samp_split: true
  sample_id_n: "151673"
  scaler_name: minmax
  st_split: false
lib_params:
  manual_seed: 2634
model_params:
  celldart_kwargs:
    bn_momentum: 0.01
    emb_dim: 64
  model_version: bnfix_minmax_samp_split
train_params:
  alpha: 0.6
  alpha_lr: 5
  batch_size: 512
  early_stop_crit: 100
  early_stop_crit_adv: 10
  initial_train_epochs: 10
  lr: 0.001
  min_epochs: 10
  min_epochs_adv: 10
  n_iter: 3000
  pretraining: true
  reverse_val: true
