data_params:
  all_genes: false
  data_dir: data
  n_markers: 20
  n_mix: 8
  n_spots: 20000
  sample_id_n: '151673'
  scaler_name: celldart
  st_split: false
  train_using_all_st_samples: false
model_params:
  celldart_kwargs:
    bn_momentum: 0.01
    emb_dim: 64
  model_version: celldart1_bnfix
torch_params:
  manual_seed: 1205
train_params:
  alpha: 0.6
  alpha_lr: 5
  batch_size: 512
  early_stop_crit: 100
  early_stop_crit_adv: 10
  initial_train_epochs: 10
  min_epochs: 10
  min_epochs_adv: 10
  n_iter: 3000
