data_params:
  all_genes: false
  data_dir: data
  dset: mouse_cortex
  n_markers: 80
  n_mix: 5
  n_spots: 100000
  samp_split: true
  sc_id: GSE115746
  scaler_name: minmax
  st_id: spotless_mouse_cortex
  st_split: false
lib_params:
  manual_seed: 4092159132
model_params:
  adda_kwargs:
    bn_momentum: 0.1
    emb_dim: 64
  model_version: gen_spotless_oracle-2691-LONG-TRAIN
train_params:
  adam_beta1: 0.5
  alpha: 1
  batch_size: 8
  dis_loop_factor: 10
  enc_lr: 2.0e-06
  epochs: 200
  initial_train_epochs: 200
  initial_train_lr: 0.0001
  pretraining: true
  reverse_val: false
