data_params:
  all_genes: false
  data_dir: data
  dset: pdac
  n_markers: 20
  n_mix: 50
  n_spots: 100000
  one_model: true
  samp_split: false
  sc_id: CA001063
  scaler_name: standard
  st_id: GSE111672
  st_split: false
lib_params:
  manual_seed: 2494379989
model_params:
  adda_kwargs:
    bn_momentum: 0.1
    emb_dim: 32
  model_version: final
train_params:
  adam_beta1: 0.5
  alpha: 1
  batch_size: 256
  dis_loop_factor: 10
  enc_lr: 0.0002
  epochs: 200
  initial_train_epochs: 100
  initial_train_lr: 0.0001
  pretraining: true
  reverse_val: false
