data_params:
  all_genes: false
  data_dir: data
  n_markers: 20
  n_mix: 8
  n_spots: 20000
  sample_id_n: "151673"
  scaler_name: minmax
  st_split: false
model_params:
  adda_kwargs:
    bn_momentum: 0.01
    emb_dim: 64
  model_version: minmax_bnfix_adam_beta1_5
lib_params:
  manual_seed: 263
train_params:
  adam_beta1: 0.5
  alpha: 2
  batch_size: 1024
  dis_loop_factor: 5
  early_stop_crit: 100
  early_stop_crit_adv: 200
  enc_lr: 0.0002
  epochs: 200
  initial_train_epochs: 100
  min_epochs: 40.0
  min_epochs_adv: 80.0
  pretraining: true
