data_params:
  all_genes: false
  data_dir: data
  dset: "mouse_cortex"
  n_markers: 20
  n_mix: 10
  n_spots: 20000
  sample_id_n: "151673"
  scaler_name: standard
  sc_id: "spotless_mouse_cortex"
  st_id: "spotless_mouse_cortex"
  st_split: false
  samp_split: true
  train_using_all_st_samples: false
model_params:
  adda_kwargs:
    bn_momentum: 0.01
    emb_dim: 64
  model_version: standard_bnfix_adam_beta1_5_spotless
lib_params:
  manual_seed: 18
train_params:
  adam_beta1: 0.5
  alpha: 2
  batch_size: 16
  dis_loop_factor: 5
  early_stop_crit: 100
  early_stop_crit_adv: 200
  enc_lr: 0.00002
  epochs: 200
  initial_train_lr: 0.0002
  initial_train_epochs: 100
  min_epochs: 40.0
  min_epochs_adv: 80.0
  pretraining: true
