data_params:
  all_genes: false
  data_dir: data
  dset: "dlpfc"
  n_markers: 20
  n_mix: 8
  n_spots: 20000
  sample_id_n: "151673"
  scaler_name: standard
  sc_id: "GSE144136"
  st_id: "spatialLIBD"
  st_split: false
  samp_split: true
model_params:
  adda_kwargs:
    bn_momentum: 0.01
    emb_dim: 64
  model_version: standard_bnfix_adam_beta1_5_samp_split
lib_params:
  manual_seed: 63
train_params:
  adam_beta1: 0.5
  alpha: 2
  batch_size: 1024
  dis_loop_factor: 5
  early_stop_crit: 100
  early_stop_crit_adv: 200
  enc_lr: 0.00002
  epochs: 5
  initial_train_lr: 0.0002
  initial_train_epochs: 10
  min_epochs: 40.0
  min_epochs_adv: 80.0
  reverse_val: true
  pretraining: true
