data_params:
  all_genes: false
  data_dir: data
  dset: pdac
  n_markers: 80
  n_mix: 70
  n_spots: 100000
  one_model: true
  samp_split: false
  sc_id: CA001063
  scaler_name: standard
  st_id: GSE111672
  st_split: false
lib_params:
  manual_seed: 837520125
model_params:
  adda_kwargs:
    bn_momentum: 0.01
    emb_dim: 64
  model_version: gen_pdac-34780
train_params:
  adam_beta1: 0.5
  alpha: 1
  batch_size: 512
  dis_loop_factor: 2
  enc_lr: 2.0e-05
  epochs: 200
  initial_train_epochs: 100
  initial_train_lr: 0.0002
  pretraining: true
  reverse_val: false
