data_params:
  all_genes: false
  data_dir: data
  n_markers: 20
  n_mix: 8
  n_spots: 20000
  sample_id_n: "151673"
  scaler_name: unscaled
  st_split: false
  train_using_all_st_samples: false
model_params:
  adda_kwargs:
    bn_momentum: 0.99
    emb_dim: 64
  model_version: unscaled_nobnfix_adam_beta1_5
lib_params:
  manual_seed: 76
train_params:
  adam_beta1: 0.5
  alpha: 2
  batch_size: 1024
  dis_loop_factor: 5
  early_stop_crit: 100
  early_stop_crit_adv: 200
  enc_lr: 0.0002
  epochs: 200
  initial_train_epochs: 100
  min_epochs: 40.0
  min_epochs_adv: 80.0
