data_params:
  all_genes: false
  data_dir: data
  dset: mouse_cortex
  n_markers: 80
  n_mix: 5
  n_spots: 100000
  samp_split: true
  sc_id: GSE115746
  scaler_name: standard
  st_id: spotless_mouse_cortex
  st_split: false
lib_params:
  manual_seed: 3731364301
model_params:
  dann_kwargs:
    alpha_: 1
    dis_dropout_factor: 1
    dropout: 0.2
    emb_dim: 64
    enc_hidden_layer_sizes:
      - 512
      - 512
    enc_out_act: null
  model_version: final
train_params:
  adv_opt_kwargs:
    betas:
      - 0.5
      - 0.999
    eps: 1.0e-07
    lr: 0.002
    weight_decay: 0.01
  batch_size: 8
  early_stop_crit: 100
  early_stop_crit_adv: 500
  epochs: 10
  lambda: 1
  min_epochs: 40
  min_epochs_adv: 100
  plateau_kwargs:
    factor: 0.5
    min_lr: 2.0e-06
    patience: 50
    verbose: true
  pretraining: false
  reverse_val: false
  source_first: false
  two_step: true
