data_params:
  all_genes: false
  data_dir: data
  dset: mouse_cortex
  n_markers: 40
  n_mix: 10
  n_spots: 100000
  samp_split: true
  sc_id: GSE115746
  scaler_name: standard
  st_id: spotless_mouse_cortex
  st_split: false
lib_params:
  manual_seed: 169465162
model_params:
  dann_kwargs:
    alpha_: 2
    dis_dropout_factor: 0.5
    dropout: 0.5
    emb_dim: 32
    enc_hidden_layer_sizes:
      - 512
      - 512
    enc_out_act: true
  model_version: gen_spotless_oracle-351969
train_params:
  adv_opt_kwargs:
    betas:
      - 0.5
      - 0.999
    eps: 1.0e-07
    lr: 1.0e-05
    weight_decay: 0.1
  batch_size: 8
  early_stop_crit: 100
  early_stop_crit_adv: 500
  epochs: 500
  lambda: 0.5
  min_epochs: 40
  min_epochs_adv: 100
  plateau_kwargs:
    factor: 0.5
    min_lr: 2.0e-06
    patience: 50
    verbose: true
  pretraining: false
  reverse_val: false
  source_first: true
  two_step: false
